name: compare_all_cartpole

display_keys: [algo, dataset, model, lr, hidden, layers, seed]

base:
  dataset: cartpole
  model: mlp
  epochs: 100
  batch: 128
  device: cuda
  robustness: none
  verbose: 0
  input-noise-training: 0.0

grid:
  algo: [bp, softhebb, kp]
  seed: [0]
  lr: [1e-3]
  hidden: [128, 512, 1024]
  layers: [2, 5, 10]
