name: compare_all_cartpole

display_keys: [algo, dataset, lr, seed, rl-algo, rl-steps]

base:
  dataset: cartpole
  model: mlp
  epochs: 100
  batch: 128
  device: cuda
  robustness: none
  verbose: 0
  rl-steps: 500_000
  rl-algo: ppo
  weight-decay: 0.0
  optimizer: ano

grid:
  algo: [bp, softhebb, kp]
  seed: [0, 1, 2]
  lr: [1e-3]
